### ISSUE TITLE
Link sub resources from item and property get endpoints

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/QueryrAPI#13]
Have `/items/$id` contain `"label_url": "fullpath/items/$id/label"`, etc.

This is especially important if #28 is solved by moving this data out of its current location.

Similar to https://api.github.com/users/JeroenDeDauw

**Comment by addshore** [comment]
Yes! :)

**Comment by JeroenDeDauw** [comment]
Done by https://github.com/JeroenDeDauw/QueryrAPI/commit/82ee42dae379414ba1d13a1484a6c81fcd260e67 and deployed
