### ISSUE TITLE
UnexpectedValueException caused no continue data to be output

### ISSUE THREAD

**Issue by addshore** [JeroenDeDauw/QueryrAPI#22]
The below happened to me and resulted in me not knowing where to continue in the export :(

```
Importing entity 3246552: Q413601......... Entity imported.

Importing entity 3246553: Q413623.....


  [UnexpectedValueException]
  The stream or file "/srv/apps/Replicator/src/../var/log/error.log" could not be                         opened: failed to open stream: Permission denied



import:gz [-c|--continue [CONTINUE]] [-m|--max [MAX]] [--] <file>
```

I mean, this might be a nasty idea, but it would be great for the general app, or something somewhere to catch all exceptions and output some stuff before re throwing them?
Or something like that

**Comment by JeroenDeDauw** [comment]
How did the abort happen? End of limit, manual abort, or some error?

> I mean, this might be a nasty idea, but it would be great for the general app, or something somewhere to catch all exceptions and output some stuff before re throwing them?

Could also just fix the permission issue so the write to the log would work :D

Anyway, wrong repo. And already an issue to track this: https://github.com/JeroenDeDauw/Replicator/issues/3

**Comment by addshore** [comment]
Bah, how on earth did I manage to report this to the wrong place.... heh.
