### ISSUE TITLE
Labels vs ids in the item response format

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/QueryrAPI#36]
Preliminary item response format documentation: http://queryr.wmflabs.org/about/docs/item

The premise is that for users that want to do something simple "with Wikipedia data" and that do not know about Wikidata having a way to not force them to deal with item and property ids is nice. At the same time people will want to be able to have the stability of using the ids as well.

A first question is whether this premise is correct: does providing access by labels add real value? Assuming it does, both classes of use cases can be served. However, it's still useful to know which class is more important for determining which one gets served by default in places where such a choice needs to be made.

Below are different approaches to serving both classes of use cases:
## Two formats

This is pretty straightforward: one format like the current one, and one in which IDs are used (both for the properties and for item references).
## Embedded labels/ids

Have label keys and embed the ids

``` json
data: {
    "population": {
        "property_id": "P123",
        "value": 9001,
        "type": "number"
    }
}
```

Or have id keys and embed the labels

``` json
data: {
    "P123": {
        "label": "population",
        "value": 9001,
        "type": "number"
    }
}
```

One can of course not have keys at all and embed both, [as done by chantek](http://api.haykranen.nl/wikidata/entity?q=Q328523).
## Map from id to label

Use ids as keys and provide a map from label to id

``` js
data: {
    "capital city": {
        "value": "Berlin",
        "type": "string"
        // Something here would need to change so the user knows this an item id
    }
},
item_ids_by_label: {
    "Berlin": "Q64"
},
property_ids_by_label: {
    "capital city": "P123"
}
```

**Comment by JeroenDeDauw** [comment]
These are presumably not all approaches, and the ones listed can be combined in various manners. What do you think is the best combination of trade offs and why?

Somewhat related: [How lean should the item and property endpoints be?](https://github.com/JeroenDeDauw/QueryrAPI/issues/28)

**Comment by jane023** [comment]
What about the links to modelling items such as in this item for "calendar model" and "units"? Do these need labels? It seems obvious from the data returned, but I am not sure.
http://queryr.wmflabs.org/api/items/Q185372

**Comment by JeroenDeDauw** [comment]
The [possible format demo'd here](https://gist.github.com/JeroenDeDauw/fc17f9fdd2e4567a17ff) uses the embedding approach. Comments welcome.

**Comment by JeroenDeDauw** [comment]
> What about the links to modelling items such as in this item for "calendar model" and "units"? Do these need labels? It seems obvious from the data returned, but I am not sure.
> http://queryr.wmflabs.org/api/items/Q185372

I've not put any thought into how to best deal with values of type time, quantity and coordinate yet. This seems pretty isolated and something best done when the format they reside in has been hammered out more.

Are you saying you think these should or should not include labels of linked items?

**Comment by JeroenDeDauw** [comment]
- 7441b1fdd1cbbcd9ce49a1e9931b7e158ff472cd: Indexing is now done by property id rather than label
- db11130700bef93281b5903ec285ad4773378cd4 be7ffb834b199b42bbb392bc6e0c39a223e0f2df: serialization now contains a property hash with label, id and url

**Comment by jane023** [comment]
It's hard for me to understand all of your questions, but I suppose I would use such an api for quick lookups both to retrieve Q numbers for topics/titles but also to see whether such-and-such a property exists yet. The problem with labels in general is twofold: spelling issues and language issues. For exact the same spelling across languages there is currently no way to find these as far as I know. Even if you enable "fall-back languages", then this is only one more language, though we have 100's of them now.
